### ISSUE TITLE
How to just use the label of the countries without flag

### ISSUE THREAD

**Issue by Bartolly** [halt-hammerzeit/react-phone-number-input#10]
Hi, how can I use just the label of the countries without the flags when some country is selected? 
Thanks in advance!

**Comment by halt-hammerzeit** [comment]
Closed by https://github.com/halt-hammerzeit/react-phone-number-input/commit/c51e3d84d49c487b4ac2f8ef48888397298cae81
Use `flags={ false }` in the new version.

**Comment by Bartolly** [comment]
Worked. Thanks

**Comment by Aidosmf** [comment]
Hi, how can I use coutry codes instead of country names without flag?
