### ISSUE TITLE
How to use it in angular2?

### ISSUE THREAD

**Issue by dfostic** [halt-hammerzeit/react-phone-number-input#13]
Hi All,

I am new to javascript and angular. I am trying to use library in angular2 but without any success.
Even don't know how to use it.
What should i put in component.ts?
What should i put in component.html?

Can you please give me an example?
Thank you!

**Comment by halt-hammerzeit** [comment]
This library is for `React` as its name says.
Therefore it's only usable in React setups.

**Comment by dfostic** [comment]
What is React?
Will i be able to use it in my app?

**Comment by halt-hammerzeit** [comment]
You will when you become a better web developer
