### ISSUE TITLE
possible to retrieve the country_code portion

### ISSUE THREAD

**Issue by jenlai1345** [halt-hammerzeit/react-phone-number-input#16]
Hi,
Thank you for writing this amazing tool.
I was wondering if the tool allows us to retrive the country code portion out of the inputed number?

For example, if user types in 
(310)431 8765 ---- USA number
the internationally formatted number will be +1 310 431 8765
Is there anyway that I can get the country code like 
Phone.getCountryCode ---> returns 1 

Thank you so much!

**Comment by halt-hammerzeit** [comment]
What for do you need the country code

**Comment by neekey** [comment]
+1 for this feature, since the component already has this information, I think it's better expose the complete information it has via the `onChange` callback.

For example:
```js
function handleChange({ phoneNumber, isValid, countryName, coutryCode }) {
    /* ... do you logic */
}

<Phone onChange={handleChange} />
```

It will be easier to do form validation and knowledge collection instead of calling another utils function like `isValidNumber`, or even `parse()`

**Comment by halt-hammerzeit** [comment]
One can easily get `countryCode` and `isValid` using the exported `parsePhoneNumber` function.
Until you provide valid use cases for when it's not convenient I'm not seeing any reasons to pass anything other than `value` to `onChange` handler.

**Comment by catamphetamine** [comment]
As mentioned in the linked issue, I've added a note to the readme:


To get `country` from `value` one can use `parsePhoneNumber(value)` function.

```js
import { parsePhoneNumber } from 'react-phone-number-input'

parsePhoneNumber('+12133734253').country === 'US'
```
