### ISSUE TITLE
CSS creates long blank section at the bottom of the page for iOS8

### ISSUE THREAD

**Issue by henrythe9th** [halt-hammerzeit/react-phone-number-input#17]
Hey,

Really liked your plugin but noticed that the CSS seems to cause an issue with iOS8.

As you can see from the screenshot, when when I load the demo page on an iOS8 device, the page is extended and shows a long blank section below the content:

![](https://i.imgur.com/GCTU2UI.png)

Do you know why this is happening?

Thank you!

**Comment by halt-hammerzeit** [comment]
This was due to iOS 8 not supporting `transition` and `transform`.
I added `-webkit-` prefixes for that, though in a proper environment CSS should be postprocessed with an autoprefixer.
