### ISSUE TITLE
Integration with redux-form

### ISSUE THREAD

**Issue by advance512** [halt-hammerzeit/react-phone-number-input#18]
Does this cool component offer an easy integration with `react-redux`?
Do you know of any example?

**Comment by halt-hammerzeit** [comment]
Which "integration" exactly do you mean

**Comment by advance512** [comment]
I mean, using it like this:

```
<Field
            name="phoneNumber"
            component={Phone}
            placeholder="Start typing a phone number"
            validate={required}
          />
```

without causing this:

> Warning: Failed prop type: The prop `onChange` is marked as required in `Input`, but its value is `undefined`.

and this:

> Warning: Unknown props `input`, `meta` on <input> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop

**Comment by halt-hammerzeit** [comment]
> The prop onChange is marked as required in Input

I think `onChange` is required otherwise it wouldn't make any sense

> Warning: Unknown props input, meta on tag. 

Which tag

**Comment by advance512** [comment]
The code I used is exactly as I've shown you. 
`redux-form` is supposed to [latch on ](http://redux-form.com/6.0.0-alpha.4/docs/api/Field.md/)to the onChange, no?

Which tag? I guess on one of the tags use by react-phone-number-input. Though that might be caused by `redux-form` itself.

**Comment by halt-hammerzeit** [comment]
`redux-form` passes `onChange` to the underlying component.
So it should and this warning shouldn't be even present.
Probably something with your code.

**Comment by advance512** [comment]
Will debug it later this month, and get back to you (and future potential users of this with redux-form).

**Comment by halt-hammerzeit** [comment]
Just found a bug when using with `redux-form` caused by `onBlur(event)`.
Fixed: https://github.com/halt-hammerzeit/input-format/commit/02fe2b4a525bb74d5f9b5bc56ef5f44117461b6c

**Comment by catamphetamine** [comment]
FYI: fixed another `redux-form` `onBlur()` bug which prevented phone number validation from working correctly

**Comment by swoopapp** [comment]
Hey @advance512 did you ever find the solution here? I'm using redux-form and I'm trying to achieve the same thing. I can't seem to get the logic for onChange to work

<Field
                                          // className={classes.input}
                                          component={PhoneInput}
                                        
                                          // {
                                          //   this.isDesktopScreenSize
                                          //     ? renderNumberTextField
                                          //     : renderMobileNumberTextField
                                          // }
                                          disabled={
                                            this.props.OrderOverviewReducer
                                              .isRequesting
                                          }
                                          label="Phone"
                                          name="phone"
                                          normalize={phoneNumber}
                                          onChange={() => setTimeout(handleSubmit(params => this.updatePhone(params)))}
                                          props= {{
                                            country:"US",
                                            name:"phone",
                                            placeholder:"Enter Mobile number",
                                            // value={this.state.phone}
                                            // onChange:{updatePhone}
                                          }}
                                        />
