### ISSUE TITLE
Flags aren't displayed on first render

### ISSUE THREAD

**Issue by mbrevda** [halt-hammerzeit/react-phone-number-input#20]
When the element is first rendered, it seems the appropriate flag isn't set until the number is edited. Is that a bug or did I miss something?

![2017-03-16 18_59_04](https://cloud.githubusercontent.com/assets/293004/24008584/b5964cea-0a7a-11e7-80e1-3992d3cfd4d3.gif)

**Comment by halt-hammerzeit** [comment]
thx, fixed in `react-phone-number-input@0.7.11`

**Comment by mbrevda** [comment]
that was fast 🚀, thanks!

**Comment by mbrevda** [comment]
It looks like react isn't thrilled about this change:

<img width="987" alt="screen shot 2017-03-17 at 1 36 55 pm" src="https://cloud.githubusercontent.com/assets/293004/24041720/58b7daa0-0b17-11e7-9374-137b898d16b5.png">

**Comment by halt-hammerzeit** [comment]
This property is now stripped in `react-phone-number-input@0.7.12`

**Comment by orlandodemauro** [comment]
@halt-hammerzeit I'm still able to reproduce the issue on package 0.8.6

```
<Phone
          placeholder={placeholder}
          value={value}
          onChange={this.handleChange}
          onBlur={this.handleBlur}
          disabled={disabled}
        />
```
value is "+353831123456"

**Comment by halt-hammerzeit** [comment]
And I'm not, everything works for me with the latest version and `+353831123456`
