### ISSUE TITLE
value only works on local state variables?

### ISSUE THREAD

**Issue by hynese** [halt-hammerzeit/react-phone-number-input#22]
When I do:

`<Phone placeholder="Phone number" value={this.state.phone} onChange={(phone)=>{self.onPhoneChange(phone)}} /> {this.state.phone}`

it renders correctly. The correct phone number also appears underneath.

However, when I do (I'm storing my state in a redux pattern):

`<Phone placeholder="Phone number" value={this.props.vars.member.phone} onChange={(phone)=>{self.onPhoneChange(phone)}} /> {this.props.vars.member.phone}`

The field is empty! The correct phone number (this.props.vars.member.phone) appears underneath which is confusing...

It appears it only works if the value is stored in the component's local state???

**Comment by halt-hammerzeit** [comment]
No, there's no difference where is the value taken from

**Comment by hynese** [comment]
When my page loads initially, `this.props.vars.member.phone=''`

After a few short moments, `this.props.vars.member.phone='+447753849283'`

This state update doesn't appear in `<Phone ... />`

**Comment by hynese** [comment]
OK... I seem to have figured it out now...


Before I was doing:

`<Phone placeholder="Phone number" value={this.props.vars.member.phone} onChange={(phone)=>{self.onPhoneChange(phone)}} />`

However, if I do the following, it works:

```
var _phone=this.props.vars.member.phone;

render(){
    ...
    <Phone placeholder="Phone number" value={_value} onChange={(phone)=>{self.onPhoneChange(phone)}} />
    ...
}
```

Thank you so much!
