### ISSUE TITLE
Inconsistent with Google's result

### ISSUE THREAD

**Issue by yogsky** [halt-hammerzeit/react-phone-number-input#23]
For example, given an invalid phone in Israel: 014677822

- IL === israel (iso country code)
- 01 === phone num areacode
- 4677822 === phone num

[Google's validator](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) detects this as an invalid number (which is the result I want)

but when testing this given value on this module's react component, I get that it is valid.

is this maybe the result of the fewer metadata items ?

I have had a few more of these inconsistencies with other values

**Comment by halt-hammerzeit** [comment]
Yes, Google's validator uses the full metadata, so stricter validation is possible after compiling custom metadata as described in the README
