### ISSUE TITLE
Ability to use default browser select menu?

### ISSUE THREAD

**Issue by zthornto** [halt-hammerzeit/react-phone-number-input#24]
Hi,

Thanks for this package, it has come in very handy. This is more of a request than it is a bug (sorry), but i'm curious if there is a way to use the browser default select behavior for the expanded country picker instead of the responsive-ui version.

If not, this could end up being a pretty handy feature. I have multiple select dropdowns on my form, and it's a bit jarring when the country picker appears differently than the others once expanded. This is especially important on mobile, as the default ios/android option pickers are familiar and easy to use on touch devices.

**Comment by halt-hammerzeit** [comment]
Implemented in the latest version

**Comment by halt-hammerzeit** [comment]
`<Phone ... nativeExpanded .../>`
