### ISSUE TITLE
Country code +44 for uk not working

### ISSUE THREAD

**Issue by miteshyugtia** [halt-hammerzeit/react-phone-number-input#26]
on insert country code +44 does not change the flag of country. All other code are working fine .
![notworking](https://cloud.githubusercontent.com/assets/27283444/24908221/e25ad054-1edc-11e7-87e6-c84577cbed49.png)
![working](https://cloud.githubusercontent.com/assets/27283444/24908241/f19ec886-1edc-11e7-96c2-e1d0c3032e36.png)

**Comment by halt-hammerzeit** [comment]
Because `"44":["GB","GG","IM","JE"]`
https://github.com/halt-hammerzeit/libphonenumber-js/blob/master/metadata.min.json

**Comment by miteshyugtia** [comment]
Thanks for Help @halt-hammerzeit
