### ISSUE TITLE
prop value change does not propagating to the input 

### ISSUE THREAD

**Issue by jyxt** [halt-hammerzeit/react-phone-number-input#29]
We have a component that wraps <Phone value={this.state.number} />, when value is updated, the underlying input value is not updated for some reason even though <Phone />'s prop value is update . See screenshot

![image](https://cloud.githubusercontent.com/assets/2034465/25060980/1058894e-2179-11e7-90db-9715d7162351.png)

**Comment by halt-hammerzeit** [comment]
I don't understand what you're saying.
Explain with code snippets.

**Comment by halt-hammerzeit** [comment]
I guess I get what you mean:

```js

					<ReactInput
						{ ...input_props }
						ref={ ref => this.input = ref }
						value={ this.state.value }
```

So the input value is maintained in state and when the property changes it's not updated in state.
I'll implement the update.

**Comment by halt-hammerzeit** [comment]
I released the new version, try it.
