### ISSUE TITLE
Custom className on input field

### ISSUE THREAD

**Issue by odannyc** [halt-hammerzeit/react-phone-number-input#31]
I would like to add a custom className to the input field, I'm using bootstrap so I would like it to be `form-control` but currently it defaults to: `rrui__input react-phone-number-input__phone`

When trying to add `className="form-control"` it'll add that class to the outer div and not the input field.

**Comment by halt-hammerzeit** [comment]
Added `inputClassName`. Install the latest version.

**Comment by odannyc** [comment]
Awesome, thanks!
Thanks for the speedy response BTW
