### ISSUE TITLE
Expose `asYouType`  from `libphonenumber-js` as `libphonenumber.asYouType`

### ISSUE THREAD

**Issue by VillainJoKeR** [halt-hammerzeit/react-phone-number-input#32]
Hi, 
I am working on a case where I need to make use of  `asYouType` programatically to check whether user is typing a phone number or an email address. It does not look appropriate importing a "dependency" like this.

    import { asYouType } from 'libphonenumber-js' 
    
    ... // some stuff
    if (new asYouType().input(username).length) {
      // phone number
    } else {
      // email or something else
    }

Let me know if I got it wrong and I should be using some other approach

**Comment by halt-hammerzeit** [comment]
Why doesn't it look appropriate to you
