### ISSUE TITLE
Sorting by value in localization dictionary

### ISSUE THREAD

**Issue by mitkinstas** [halt-hammerzeit/react-phone-number-input#34]
I am use custom localization dictionary:
`// { International: 'Международный', RU: 'Россия', US: 'США', ... }
dictionary : PropTypes.objectOf(PropTypes.string),`
But the elements are sorted by key: AF, AX, AS, AD...
Whether it is possible to add sorting by value?

**Comment by halt-hammerzeit** [comment]
Implemented in the latest version (only in modern browsers though)
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare
(not in IE10, not in Safari)

**Comment by mitkinstas** [comment]
Thanks for reply!
Now you can see the error:
`a.localeCompare is not a function`
I am create PR for fix it - https://github.com/halt-hammerzeit/react-phone-number-input/pull/35
