### ISSUE TITLE
Entering a Hungarian phone number breaks formatter

### ISSUE THREAD

**Issue by ha0rex** [halt-hammerzeit/react-phone-number-input#36]
Hi! First of all, many thanks for this amazing component! I've noticed a bug when I was trying to enter a Hungarian phone number. 
For example: +36 30 123 4567

When I set the country select to Hungarian, and type in the rest:
301234567

It turns into: (30) 123 7456.

This bug exists on the demo site as well.

Many thanks for your help, and keep up the good work! :)

Regards,
Levi

**Comment by halt-hammerzeit** [comment]
So that's the bug then

**Comment by halt-hammerzeit** [comment]
So what's the bug then?

**Comment by ha0rex** [comment]
Hi @halt-hammerzeit, please check the order of the last 4 digits. They are mixed.

**Comment by halt-hammerzeit** [comment]
I see now

**Comment by halt-hammerzeit** [comment]
Fixed via https://github.com/halt-hammerzeit/libphonenumber-js/commit/a80b3ee8eadc6a55009a05a70f95812d5116b2f8
Reinstall `libphonenumber-js` dependency
