### ISSUE TITLE
"+" breaks input

### ISSUE THREAD

**Issue by zimenskiy** [halt-hammerzeit/react-phone-number-input#37]
Can't fill in any value after putting `+` in the input with `international` param disabled
```
international={false}
```

### How to reproduce
- Disable `international` (Default country is Afghanistan)  
![](https://image.prntscr.com/image/1b6a565eade74439a0c3e3226321fce6.png)
- Fill `+` in the input  
 ![](https://image.prntscr.com/image/2fdf4f96b1e44a54828d1a752f178122.png)

After that nothing can be put in the input.
If try to delete `+` in the input and then press any number key, i.e. `1`, then `+1` will appear in the input and nothing can be put after that.

**Comment by halt-hammerzeit** [comment]
Ok, I'll prohibit inputting `+` in case of `international={false}` then

**Comment by halt-hammerzeit** [comment]
Released the new version.
It allows inputting characters after `+` but only those resulting in a valid phone number.

**Comment by zimenskiy** [comment]
Thanks! 
Also is it possible to restrict countries list just for a single contry (`countries={["VN"]} and still have a flag selector? If I do so the flag selector disappears, is it OK?

**Comment by halt-hammerzeit** [comment]
How would you use such a feature?
If only one country is allowed this usually means that the website only works in a single country therefore it doesn't need country selector or country flag.
In your case only vietnamese people would visit such a website so there's no need to display the vietnamese flag.

**Comment by zimenskiy** [comment]
Yeah, you're right. Thanks!
