### ISSUE TITLE
Need To clear value of input

### ISSUE THREAD

**Issue by miteshyugtia** [halt-hammerzeit/react-phone-number-input#39]
I am using react-phone-number-input to get phone from user.
I have save button on beside of input.
on click save button i am passing value to API after that i want to clear the value of input.

**Comment by halt-hammerzeit** [comment]
Just set the `value` to `undefined` (for example) to clear it.

**Comment by miteshyugtia** [comment]
I am using following Code :
                            <div className="row m-a-0">
                          <div className="col-sm-8 p-a-0 m-b-1">
                            <Phone
                              country={_.get(parsePhoneNumber(_.get(this.state, 'phone', '')), 'country', '')}
                              placeholder="Phone"
                              value={this.state.phone}
                              onChange={value => this.setState({phone:value})}
                              className="form-control"
                            />
                          </div>
                          <div className="col-sm-2 btn-div m-b-1">
                            <button type="button" className="btn btn-primary btn-block" onClick={(e) => this.updateMobile(e)}> Save </button>
                          </div>
                        </div>
And Function :
updateMobile(event) {
    if (event && event.preventDefault) {
      event.preventDefault();
    }
      const formData = {
        phone: this.state.phone
      };
      this.api.fetch('user/update-mobile-number', {
        method: 'PUT',
        body: JSON.stringify(formData)
      }).then(() => {
        this.setState({
          phone:'undefined '
        });
      }).catch(() => {
      });
 }

**Comment by halt-hammerzeit** [comment]
Not string 'undefined', just `undefined`

**Comment by miteshyugtia** [comment]
Still Not clear it.

**Comment by halt-hammerzeit** [comment]
Then it's an error in your code.
Perhaps you're not even calling that line.

**Comment by miteshyugtia** [comment]
No I have done console log I am getting phone : undefined.

**Comment by halt-hammerzeit** [comment]
Well, I guess if you rewrite it with just the Phone component and the reset button then it's gonna work.

**Comment by immanjeba98** [comment]
I'm facing the same issue, still not fixed yet
