### ISSUE TITLE
International and chrome autofill don't work together

### ISSUE THREAD

**Issue by alicerocheman** [halt-hammerzeit/react-phone-number-input#40]
Hi there,

Thanks for all the work!

I'm having an issue with chrome autofill. When I use '+', the country goes to international and when I use tab/enter/mouse to select the chrome autofill the value is erase. This only happens if there's only '+' in the field and no country is selected.
![phonefield](https://user-images.githubusercontent.com/21168856/27087890-86e56968-5056-11e7-98ef-56a69b02ce0c.gif)

**Comment by halt-hammerzeit** [comment]
Perhaps you could create a sample project with a step-by-step instruction.
I've just added `autocomplete="tel"` to the new release (you may try it) and tried it in my Chrome on OS X - first I input `+`, then an autocomplete list is shown, I click one of the autocomplete entries, it **becomes yellow** and the phone number inserts without any bugs.
In your screen capture I don't see yellow background.

**Comment by halt-hammerzeit** [comment]
Due to a very specific nature of this bug it's unlikely that I'll be able to reproduce it even if you create a sample project.
Seems that this may be OS-specific or browser-specific.
So far autofill works for me without any issues so you'll have to debug it yourself I guess.

**Comment by alicerocheman** [comment]
The yellow is controlled in css, I removed it on purpose...
Thanks anyway!

**Comment by catamphetamine** [comment]
FYI, this issue has been confirmed.
See: https://github.com/catamphetamine/react-phone-number-input/issues/101
No solution yet though
