### ISSUE TITLE
Doesn't work on mobile

### ISSUE THREAD

**Issue by lightninglu10** [halt-hammerzeit/react-phone-number-input#41]
Hey guys, on mobile I'm having an issue where if I click the react-phone-input field, then the input field disappears and a keyboard doesn't pop up so I can't input a phone number.

Here's a screenshot: 

<img width="412" alt="screen shot 2017-06-16 at 10 09 38 am" src="https://user-images.githubusercontent.com/2453737/27236994-2a137dec-527c-11e7-8cc0-86d2858a5a0c.png">

**Comment by halt-hammerzeit** [comment]
The demo works on my phone (iOS 8.4).
If it doesn't work on your phone then you can try to debug it.
