### ISSUE TITLE
Text input behaves strangely after updating to React v15.6.1

### ISSUE THREAD

**Issue by coreh** [halt-hammerzeit/react-phone-number-input#42]
Hey there, I've just updated my React/ReactDOM version to `15.6.1` (from `15.4.2`) and noticed that the phone number input started behaving strangely.

Specifically, when typing out a long-form international phone number, the caret will jump to the third to last position at some point, and remain there.

<img src="https://user-images.githubusercontent.com/418473/27244365-95730202-52bc-11e7-9448-a24dd550957d.gif" width="310" height="42">

React 15.6.0 saw some [changes related to `onChange` events](https://github.com/facebook/react/pull/8575), so perhaps they could be causing this?

Thanks!

**Comment by halt-hammerzeit** [comment]
Well, i guess it has nothing to do with React because if you go to the demo page and then input `+55 12 3456 789` and then input `0` after that the caret jumps as it's captured on your animation.
So it's a bug and I'll have a look.

**Comment by coreh** [comment]
Strange, it's working normally [here](https://www.zimboli.com/#signup), with React 15.4.2.

**Comment by halt-hammerzeit** [comment]
This was a small bug in `libphonenumber-js` and it has been fixed.
https://github.com/halt-hammerzeit/libphonenumber-js/commit/ddec999d111b5510c342d9dd57c117f1241cd781

```npm install libphonenumber-js@latest```

**Comment by halt-hammerzeit** [comment]
(braces are now removed from international phone number template)

**Comment by coreh** [comment]
Thanks! 🙌
