### ISSUE TITLE
nested ReactInput value doesn't update

### ISSUE THREAD

**Issue by alicerocheman** [halt-hammerzeit/react-phone-number-input#43]
I'm facing a really weird behavior.
My component updates twice in a row, after the second update the Phone component has the latest value (the right one), the nested Input is good too, but the nested ReactInput has the previous value (wrong one).

I'm guessing #39 is the same issue.

**Comment by halt-hammerzeit** [comment]
Not understand.
Describe in more detail.

**Comment by mathieux51** [comment]
Hey, I work with @alicerocheman and we're facing this issue together. I figured a demo is a better way to show the problem. What you see in the ReactDevTools is the `Input` component inside the `Phone` component, when I hit the save button I use the `onChange` method to send my data to the server. When I receive it back I inject it in `Phone` component's `value`. We can see that the `value` changes, but `value_property` doesn't. Is that enough information ? 

Thanks for your time. 👍

![screenflow](https://user-images.githubusercontent.com/15669993/27323662-98b4fc0c-55a2-11e7-9224-c29d05882aee.gif)

**Comment by halt-hammerzeit** [comment]
@mathieux51 Ooooh, I see now.
So it wasn't changing `value_property` when the `value` was changed.
Good work finding the source of the bug.

Try the new release (`0.11.7`) and tell me if it works now.

**Comment by halt-hammerzeit** [comment]
No, dismiss `0.11.7`, use `0.11.8`.

**Comment by mathieux51** [comment]
It works !!! Thanks a lot 🙏
