### ISSUE TITLE
Css issue

### ISSUE THREAD

**Issue by MihaiChiorean** [halt-hammerzeit/react-phone-number-input#44]
In case that there are multiple inputs, when the select is open, it appears under the next input.
![initial](https://user-images.githubusercontent.com/13768069/27286749-f0c1fb28-5509-11e7-8146-6debe691a5da.png)
![expendable1](https://user-images.githubusercontent.com/13768069/27286752-f613ba58-5509-11e7-8241-dfaac8a011f3.png)
![expendable2](https://user-images.githubusercontent.com/13768069/27286753-f763790c-5509-11e7-86c8-8d89e9b77c3e.png)
![expendable3](https://user-images.githubusercontent.com/13768069/27286756-f8cb973e-5509-11e7-9645-a5e039056fe4.png)

**Comment by halt-hammerzeit** [comment]
I added a second phone input in my demo HTML file and the issue is not present.
Check your `z-index` styles.
