### ISSUE TITLE
Tabbing through fields selects the country selector instead of the phone number input

### ISSUE THREAD

**Issue by luskin** [halt-hammerzeit/react-phone-number-input#46]
When in a form with multiple fields including this package and you tab through (say email -> firstname -> phone number ... etc) the phone number field that gets hit is actually first the country selector. Since 99+% of our customers are US based phone numbers we need to ignore this tabbing. can we get a tabindex property on that country selector to not be selected when tabbing?

**Comment by halt-hammerzeit** [comment]
There is one:
https://github.com/halt-hammerzeit/react-phone-number-input/blob/24844341fa705dc6dc86d9665f42c804784fd504/source/input.js#L134
