### ISSUE TITLE
scrollIntoView

### ISSUE THREAD

**Issue by bradennapier** [halt-hammerzeit/react-phone-number-input#47]
This really needs a solution for having scrollIntoView.  I can set a ref and try to do it all manually but then i have no way to know when the international dropdown is open or not so I can't really use that at all.

So I would think taht:

1. Need either an `onClick` handler on the international dropdown icon
2. Need either a automaticallyScrollIntoView prop for the dropdown or need a way to easily get ahold of the dropdown ref so we can call `ref.scrollIntoView()` on it manually if needed.

Right now the dropdown opens in my window and its cut off and there is no solution other than maybe putting a fixed div on top of it to capture the click event manually which is pretty darn hacky

![image](https://user-images.githubusercontent.com/15365418/27891298-e77b7084-61ad-11e7-855a-fcd640a75e2d.png)

![image](https://user-images.githubusercontent.com/15365418/27891303-f01c7bb6-61ad-11e7-965c-5147a371b8f8.png)

![image](https://user-images.githubusercontent.com/15365418/27891307-f6b6044c-61ad-11e7-9a97-de93a3b2ee8c.png)

**Comment by bradennapier** [comment]
I added both `onDropdown` and `automaticallyScrollIntoView` in https://github.com/halt-hammerzeit/react-phone-number-input/pull/48

I also removed es6 from the gitignore so you are welcome to install it and try it out 

```js
yarn add https://github.com/Dash-OS/react-phone-number-input.git
```

```js
npm install --save https://github.com/Dash-OS/react-phone-number-input.git
```

**Comment by halt-hammerzeit** [comment]
What's the original issue?
It's not clear from your description.

**Comment by halt-hammerzeit** [comment]
So I guess what you wanted to achieve is to scroll the dropdown list "into view" so that it's visible entirely.
Well, that's understandable.
I guess it would make sense to implement it as the default behaviour.

**Comment by halt-hammerzeit** [comment]
I closed the PR you submitted due to containing no code changes.
I can look at your solution for this if you submit a proper PR.

**Comment by bradennapier** [comment]
Updated to show the file changes that were made.  You must have only looked at the last of the 3 commits which was me adding the code to the repo so i could install it directly: https://github.com/halt-hammerzeit/react-phone-number-input/pull/48

**Comment by halt-hammerzeit** [comment]
I looked at your fork and implemented the `scrollIntoView` feature in a similar way.
It's on by default in the latest release.

**Comment by bradennapier** [comment]
There were a couple other fixes in the fork that I added.  For example, adding a tabIndex to the dropdown / input causes errors as you were passing the raw fields to the input which react complains about now.  

Then the timeouts thing of course.  

Thanks for moving fast on this !

**Comment by halt-hammerzeit** [comment]
Yeah, I seem to have fixed timeouts – clearing them in `componentWillUnmount()`

As for the `tabIndex`, not sure what you mean

**Comment by bradennapier** [comment]
Ok noticed you added the timeout handling.  Very nice.  I did not see that it was a prop that you could turn off though, there are times (I actually dont know when) that it can cause problems.  I only know that because of my experience with this same properly using react-select and others were complaining about it so he changed it to not be default.

**Comment by bradennapier** [comment]
https://github.com/halt-hammerzeit/react-phone-number-input/blob/master/source/input.js#L784

Here you take the props out then make the rest input_props

then here

https://github.com/halt-hammerzeit/react-phone-number-input/blob/master/source/input.js#L846

you are passing those props in with a spread operator.  

This means that if you are using the [selectTabIndex](https://github.com/halt-hammerzeit/react-phone-number-input/blob/master/source/input.js#L134) property it will be passed to ReactInput.

This value is then passed to the raw `<input />` which react then gives you an error for.

**Comment by bradennapier** [comment]
Wow nevermind, I see that it is there now.

**Comment by halt-hammerzeit** [comment]
>  I could just be crazy though :)

Yeah, because this line was added 3 months before now
https://github.com/halt-hammerzeit/react-phone-number-input/blame/master/source/input.js#L791

Anyway, your feedback was positive.
