### ISSUE TITLE
Required is prop

### ISSUE THREAD

**Issue by anish-saha** [halt-hammerzeit/react-phone-number-input#50]
I need a `required=true` prop to be passed down for a react modal in a form. However, the required prop is not passed down. Do you guys have such a prop?
It is formatted as such: 
```js
<Phone
         className={css(styles.input)}
         country="US"
         showCountrySelect={false}
         required={true}
         placeholder="Phone Number"
         onKeyPress={this.handleKeyPress}
         onChange={(e, inputType) => this.handleChange(e, "phoneNumber")}
         value = {this.state.phoneNumber}
/>
```

**Comment by halt-hammerzeit** [comment]
Not understand.
There's no `required={true}` property for this component.
Why would you need it.
Is it CSS related?
Or is it some HTML specification?

**Comment by halt-hammerzeit** [comment]
When passing

```js
<Phone
         country="US"
         required ... />
```

the resulting `<input type="tel"/>` has the `required` attribute which means it's working.
