### ISSUE TITLE
Any way to retrieve the code of the country picked ?

### ISSUE THREAD

**Issue by alicerocheman** [halt-hammerzeit/react-phone-number-input#7]
Hey,

So I'd like to retrieve the country code the user picks for the phone, for display later.

Is there any way to get that info? 

Thanks

**Comment by halt-hammerzeit** [comment]
Try `onCountryChange` with the latest version

**Comment by catamphetamine** [comment]
@alicerocheman Hello.
Why did you need this `onCountryChange` feature again?
I might be removing it in the next major version
