### ISSUE TITLE
International option can't be removed

### ISSUE THREAD

**Issue by sdejesusF** [halt-hammerzeit/react-phone-number-input#8]
Add a prop to remove the international option from the selector.

**Comment by halt-hammerzeit** [comment]
Are you passing a default country?
It will be required in this case.

**Comment by sdejesusF** [comment]
Yes, in fact I'm using a custom list of countries but the international option still is still being shown (I do something else with the country and I can't receive any other country that is not on the list). I create a PR with a prop to disable the international option.

**Comment by halt-hammerzeit** [comment]
No, I'll do it without a PR

**Comment by halt-hammerzeit** [comment]
So, you need to constrain the list of countries to a certain subset?
This will require more than just removing the International option.
Perhaps this will also mean prohibiting + sign from being entered.
Do you think that will do?

**Comment by halt-hammerzeit** [comment]
Also, would a property like `countries={['RU', 'DE', 'FR', ...]}` be a better solution in your case than passing the options list?

**Comment by sdejesusF** [comment]
yes, I use the list of countries like that (but as an object with the label and value) and it's restricting the countries but also it's adding the manual option to add another country. But I only work with those countries I don't want the user type a phone number for another country. But the lock option remove the whole list.

**Comment by halt-hammerzeit** [comment]
So, to finalize, I'm adding a new property:

```js
countries={['RU', 'DE', 'FR', ...]}
```

And you pass a list of country codes instead of a list of options.
Then, if `countries` is a list of strings then it's also automatically restricting the  list of possible countries and prohibiting the entering of "+" sign.

Would that solve the issue?

**Comment by sdejesusF** [comment]
Yes, that will work

**Comment by halt-hammerzeit** [comment]
Ok, I'll do that later today or tomorrow.

**Comment by sdejesusF** [comment]
Ok, thx again!

**Comment by sdejesusF** [comment]
BTW, when I use the `country={countryStateValue}` if the state country change the component doesn't change the country.

**Comment by halt-hammerzeit** [comment]
Fixed in the new version

> BTW, when I use the country={countryStateValue} if the state country change the component doesn't change the country.

Fixed in the new version

**Comment by sdejesusF** [comment]
Hi,
After the lasted update I'm getting this error `Unexpected token export` I think it's related with libphonenumber and es6

**Comment by halt-hammerzeit** [comment]
Yeah, I had this error on my machine.
How are you bundling your code?

**Comment by halt-hammerzeit** [comment]
Ok, I found where the issue originated.

`Unexpected token export` is caused by `import ... from 'libphonenumber-js/custom.es6` inside `index.es6.js`.
`index.es6.js` is marked as a `module` so only ES6-enabled bundlers would include it.
But, for some reason, Webpack 2 seemed to not recurse into that `libphonenumber-js/custom.es6` import to process its ES6 export module syntax.

Anyway, whatever the issue was, I rewrote the ES6 module exports today for both `libphonenumber-js` and `react-phone-number-input` and it seems working now.
Try the latest release.

**Comment by sdejesusF** [comment]
Hi
Yeah, it worked! But now there isn't way to remove the countries selector ?

**Comment by halt-hammerzeit** [comment]
To remove countries selector means that you have only a single country allowed.
And that means passing `countries={['US']}` property.

**Comment by halt-hammerzeit** [comment]
Does it work in your case?

**Comment by halt-hammerzeit** [comment]
```js
	// Can a user change the default country or not.
	can_change_country()
	{
		const { countries } = this.props

		// If `countries` is empty,
		// then only "International" option is available,
		// so can't switch it.
		//
		// If `countries` is a single allowed country,
		// then cant's switch it.
		//
		return countries.length > 1
	}

        render()
        {
				{ this.can_change_country() &&
					<Select ... /> }
        }
```

**Comment by sdejesusF** [comment]
Yeah, that works thank you! maybe in the future having the option to not show them so they can be controlled from an external selector would be useful.

**Comment by halt-hammerzeit** [comment]
I could add such a feature if someone tells me why the default Select doesn't suit their needs.

**Comment by sdejesusF** [comment]
<img width="890" alt="screen shot 2017-01-29 at 4 44 40 pm" src="https://cloud.githubusercontent.com/assets/10758298/22408682/71adda0e-e642-11e6-82ad-26ceaab5eb9b.png">
For example for some forms I have to keep the style (also the address is autocompleted by the selected country and having it inside the phone number you won't know which country use or if they like to change it the have to change it inside the phone number field even if they are not filling it. A little weird for the end user) and right now I can do it but it's tricky.

**Comment by halt-hammerzeit** [comment]
Ok, that's justifiable, try the new release and `showCountrySelect={ false }`

**Comment by sdejesusF** [comment]
Nice! thx once again!

**Comment by evgar** [comment]
@catamphetamine I think It would be good idea to add "showCountrySelect" prop to documentation.
Thanks!
